- docs/_config.yml
- docs/_sass/minima/_base.scss
> Change site-wide files.

- docs/AboutUs.md
- docs/team/asherhy.md
> Branch asher's about us

- docs/UserGuide.md
> Add entries for "join" and "mates" in the User Guide Features section

- docs/DeveloperGuide.md
> Update the Developer Guide's Non-Functional Requirements section

- docs/DeveloperGuide.md
Added in user stories. I have converted the ones in the word document into this format and removed some that I felt were duplicates. I also tried adding the "so that I can" part to most user stories for those that I could think of.
> Update Developer's Guide

- src/main/java/seedu/address/model/AddressBook.java
> Fix integration-related bugs

- src/main/java/seedu/address/ui/ListPanel.java
> Fix list panel to update correctly after commands

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddGCommand.java
- src/main/java/seedu/address/logic/parser/AddGCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/group/Group.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> Add people to group

- docs/UserGuide.md
> Update storage-related stuff in the user guide

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/UserPrefsTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
> Update storage-related naming

- src/main/java/seedu/address/logic/commands/AddGroupCommand.java
- src/main/java/seedu/address/logic/commands/AddTaskCommand.java
- src/main/java/seedu/address/model/task/Task.java
#239 
Resolves #245 
Resolves #261
> Fix ped bugs

- src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
- src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
> DeleteTask test class

- src/main/java/seedu/address/logic/parser/JoinGroupCommandParser.java
> Fix bug of not person not being required in addG command.

- docs/team/jayasting98.md
> Update Project Portfolio Page (Jay)

- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/testutil/GroupUtil.java
- src/test/java/seedu/address/testutil/TaskUtil.java
> Add testing for AddressBookParser

- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/commands/UndoCommand.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/HelpCommandTest.java
> Add tests for CommandResult

- src/test/java/seedu/address/commons/core/ConfigTest.java
- src/test/java/seedu/address/commons/core/VersionTest.java
- src/test/java/seedu/address/logic/commands/GroupCommandTest.java
> Increase code coverage

- src/main/java/seedu/address/storage/JsonAdaptedGroup.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
- src/test/java/seedu/address/testutil/GroupBuilder.java
- src/test/java/seedu/address/testutil/GroupUtil.java
- src/test/java/seedu/address/testutil/TypicalGroups.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
> Update tests for JsonAdaptedGroup

- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
> Update tests for JsonAdaptedPerson

- src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
- src/test/java/seedu/address/testutil/TaskBuilder.java
> Add tests for JsonAdaptedTask

- src/main/java/seedu/address/storage/Id.java
- src/test/java/seedu/address/storage/IdTest.java
> Update tests for storage ID

- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
> Improve code quality of JsonSerializableAddressBook

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AddGroupCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/EditGroupCommand.java
- src/main/java/seedu/address/logic/commands/JoinGroupCommand.java
- src/main/java/seedu/address/logic/commands/RemoveCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
- src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/EditGroupCommandTest.java
- src/test/java/seedu/address/logic/commands/JoinGroupCommandTest.java
- src/test/java/seedu/address/logic/commands/MarkAsDoneCommandTest.java
- src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
> Add test cases for undo command

- docs/UserGuide.md
Some additional changes to the UG.
> Add changes to the UG.

- src/main/java/seedu/address/ui/Card.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/GroupCard.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/ResultDisplay.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/java/seedu/address/ui/TaskCard.java
- src/main/java/seedu/address/ui/Ui.java
- src/main/java/seedu/address/ui/UiManager.java
- src/main/java/seedu/address/ui/UiPart.java
> Improve storage component code quality and add Javadoc comments

- src/main/java/seedu/address/logic/parser/AddressBookParser.java
> Fix application state
